language: objective-c
osx_image: xcode8

# cache: cocoapods
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --version 1.1.0.rc.2 --no-document
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.17.2/Carthage.pkg" && sudo installer -pkg "Carthage.pkg" -target / && rm "Carthage.pkg"

script:
  - carthage bootstrap
  - set -o pipefail && xcodebuild -project DipUI/DipUI.xcodeproj -scheme DipUI -destination "platform=macOS" test | xcpretty
  - set -o pipefail && xcodebuild -project DipUI/DipUI.xcodeproj -scheme DipUI -destination "platform=iOS Simulator,name=iPhone 6S" test | xcpretty
  - set -o pipefail && xcodebuild -project DipUI/DipUI.xcodeproj -scheme DipUI -destination "platform=tvOS Simulator,name=Apple TV 1080p" test | xcpretty
  - set -o pipefail && xcodebuild -project DipUI/DipUI.xcodeproj -scheme DipUI -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" build | xcpretty
  - pod repo update --silent && pod spec lint
  - carthage build --no-skip-current

notifications:
  email: false
